name: tenpureto
version: 0.6.3
author: "Roman Timushev"
maintainer: "rtimush@gmail.com"
github: "tenpureto/tenpureto"
homepage: "https://tenpureto.org"
copyright: "2019 Roman Timushev"
synopsis: "Simple and flexible project templates"
description: "Please see the README on GitHub at <https://github.com/tenpureto/tenpureto#readme>"

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - random
  - either
  - text
  - replace-attoparsec
  - attoparsec
  - path
  - path-io
  - directory
  - containers
  - semigroupoids
  - algebraic-graphs
  - transformers
  - prettyprinter
  - prettyprinter-ansi-terminal
  - ansi-terminal
  - terminal-size
  - typed-process
  - optparse-applicative
  - yaml
  - libyaml
  - conduit
  - aeson
  - filepattern
  - parsec
  - file-embed
  - monad-memo
  - polysemy >= 1.3.0.0
  - polysemy-plugin

ghc-options: -O2 -fplugin=Polysemy.Plugin -flate-specialise -fspecialise-aggressively -optP-Wno-nonportable-include-path

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - OverloadedStrings

library:
  source-dirs: src

executables:
  tenpureto:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tenpureto

tests:
  tenpureto-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tenpureto
      - sydtest
      - sydtest-hedgehog

      - tasty
      - tasty-discover
      - tasty-smallcheck
      - tasty-hunit
      - tasty-hedgehog
      - smallcheck
      - hedgehog
