name:                tenpureto
version:             0.1.3
author:              "Roman Timushev"
maintainer:          "rtimush@gmail.com"
github:              "rtimush/tenpureto"
copyright:           "2019 Roman Timushev"
synopsis:            "Simple and flexible project templates"
description:         "Please see the README on GitHub at <https://github.com/rtimush/tenpureto#readme>"

dependencies:
- base >= 4.7 && < 5
- bytestring
- either
- text
- text-icu
- text-regex-replace
- path
- path-io
- directory
- containers
- insert-ordered-containers
- exceptions
- mtl
- transformers
- logging-effect
- prettyprinter
- prettyprinter-ansi-terminal
- terminal-size
- typed-process
- optparse-applicative
- yaml
- aeson
- dotgen
- Glob

library:
  source-dirs: src

executables:
  tenpureto:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenpureto

tests:
  tenpureto-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenpureto
    - tasty
    - tasty-discover
    - tasty-smallcheck
    - tasty-hunit
    - smallcheck
