FROM ubuntu:20.04 AS build

# stack
RUN apt-get update
RUN apt-get install -y build-essential curl
RUN curl -sSL https://get.haskellstack.org/ | sh

# fpm
RUN apt-get install -y ruby ruby-dev rubygems
RUN gem install --no-ri --no-rdoc fpm

# ghc dependencies
RUN apt-get install -y libncurses-dev
